"use client";

import { CheckCircle2, Sparkles } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import { CONFIG } from "@/lib/config";
import { addClaimedSite, type BusinessType } from "@/lib/store";

const routeByType: Record<BusinessType, string> = {
  pizza: "/demos/pizza-hildesheim",
  plumber: "/demos/plumber-hildesheim",
  gym: "/demos/gym-hildesheim",
  barber: "/demos/barber-hildesheim",
  cleaning: "/demos/cleaning-hildesheim",
  other: "/demos/pizza-hildesheim",
};

export default function GeneratorPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [businessType, setBusinessType] = useState<BusinessType>("pizza");
  const [city, setCity] = useState<string>(CONFIG.DEFAULT_CITY);
  const [businessName, setBusinessName] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [description, setDescription] = useState("");

  const [isGenerating, setIsGenerating] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [showClaimSuccess, setShowClaimSuccess] = useState(false);
  const [dotStep, setDotStep] = useState(1);

  useEffect(() => {
    const typeParam = searchParams.get("type");
    const cityParam = searchParams.get("city");
    const nameParam = searchParams.get("name");
    const phoneParam = searchParams.get("phone");
    const descriptionParam = searchParams.get("description");
    if (
      typeParam === "pizza" ||
      typeParam === "plumber" ||
      typeParam === "gym" ||
      typeParam === "barber" ||
      typeParam === "cleaning" ||
      typeParam === "other"
    ) {
      setBusinessType(typeParam);
    }
    if (cityParam) setCity(cityParam);
    if (nameParam) setBusinessName(nameParam);
    if (phoneParam) setPhoneNumber(phoneParam);
    if (descriptionParam) setDescription(descriptionParam);
  }, [searchParams]);

  const previewAddress = useMemo(() => {
    const fallbackStreet = {
      pizza: "Marktstraße 12",
      plumber: "Almsstraße 8",
      gym: "Bahnhofsallee 21",
      barber: "Hoher Weg 5",
      cleaning: "Steingrube 14",
      other: "Innenstadt 1",
    }[businessType];
    return `${fallbackStreet}, 31134 ${city || CONFIG.DEFAULT_CITY}`;
  }, [businessType, city]);

  const previewUrl = useMemo(() => {
    const params = new URLSearchParams({
      city: city || CONFIG.DEFAULT_CITY,
      name: businessName || "My Local Business",
      phone: phoneNumber || "+49 0000 000000",
      description:
        description ||
        "A modern local business website generated by SnapLocal with fast booking and WhatsApp conversion.",
      address: previewAddress,
    });
    return `${routeByType[businessType]}?${params.toString()}`;
  }, [businessType, city, businessName, phoneNumber, description, previewAddress]);

  function resetAll() {
    setBusinessType("pizza");
    setCity(CONFIG.DEFAULT_CITY);
    setBusinessName("");
    setPhoneNumber("");
    setDescription("");
    setIsGenerating(false);
    setShowPreview(false);
    setShowClaimSuccess(false);
    setDotStep(1);
  }

  function handleGenerate(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setShowClaimSuccess(false);
    setShowPreview(false);
    setIsGenerating(true);

    const dotTimer = window.setInterval(() => {
      setDotStep((prev) => (prev >= 3 ? 1 : prev + 1));
    }, 450);

    window.setTimeout(() => {
      window.clearInterval(dotTimer);
      setIsGenerating(false);
      setShowPreview(true);
    }, 2400);
  }

  function handleClaim() {
    addClaimedSite({
      businessType,
      city: city || CONFIG.DEFAULT_CITY,
      businessName: businessName || "My Local Business",
      phoneNumber: phoneNumber || "+49 0000 000000",
      description:
        description ||
        "A modern local business website generated by SnapLocal with fast booking and WhatsApp conversion.",
      address: previewAddress,
      templateRoute: routeByType[businessType],
      previewUrl,
      claimedAt: new Date().toISOString(),
    });
    console.log("Site claimed");
    setShowClaimSuccess(true);
    window.setTimeout(() => {
      router.push("/dashboard");
    }, 1200);
  }

  return (
    <main className="min-h-screen bg-zinc-950 text-white">
      <div className="container py-10 md:py-14">
        <div className="mx-auto max-w-3xl rounded-2xl border border-zinc-800 bg-zinc-900 p-5 md:p-7">
          <p className="text-xs font-semibold uppercase tracking-wide text-cyan-300">SnapLocal Generator</p>
          <h1 className="mt-2 text-3xl font-black md:text-4xl">Generate My Website in 30 seconds</h1>
          <p className="mt-2 text-sm text-zinc-300">
            Fill in your business details, and SnapLocal will instantly assemble a high-converting website template.
          </p>

          <form onSubmit={handleGenerate} className="mt-6 space-y-4">
            <label className="block text-sm">
              <span className="mb-1 block text-zinc-300">Business type</span>
              <select
                value={businessType}
                onChange={(event) => setBusinessType(event.target.value as BusinessType)}
                className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2"
              >
                <option value="pizza">Pizza restaurant</option>
                <option value="plumber">Emergency plumber</option>
                <option value="gym">Fitness gym</option>
                <option value="barber">Barber / hair salon</option>
                <option value="cleaning">House cleaning</option>
                <option value="other">Other</option>
              </select>
            </label>

            <div className="grid gap-4 md:grid-cols-2">
              <label className="block text-sm">
                <span className="mb-1 block text-zinc-300">City</span>
                <input
                  value={city}
                  onChange={(event) => setCity(event.target.value)}
                  className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2"
                />
              </label>
              <label className="block text-sm">
                <span className="mb-1 block text-zinc-300">Business name</span>
                <input
                  required
                  value={businessName}
                  onChange={(event) => setBusinessName(event.target.value)}
                  className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2"
                />
              </label>
            </div>

            <label className="block text-sm">
              <span className="mb-1 block text-zinc-300">Phone number</span>
              <input
                required
                value={phoneNumber}
                onChange={(event) => setPhoneNumber(event.target.value)}
                className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2"
              />
            </label>

            <label className="block text-sm">
              <span className="mb-1 block text-zinc-300">Short description (optional, 1-2 sentences)</span>
              <textarea
                value={description}
                onChange={(event) => setDescription(event.target.value)}
                className="min-h-20 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2"
              />
            </label>

            <Button type="submit" size="lg" className="h-12 w-full rounded-full bg-cyan-600 text-base font-bold hover:bg-cyan-500">
              Generate My Website in 30 seconds
            </Button>
          </form>
        </div>

        {isGenerating ? (
          <div className="mx-auto mt-8 max-w-3xl rounded-2xl border border-cyan-500/30 bg-cyan-500/10 p-6 text-center">
            <Sparkles className="mx-auto h-7 w-7 text-cyan-300" />
            <p className="mt-3 text-lg font-semibold">AI is building your site{".".repeat(dotStep)}</p>
            <p className="mt-1 text-sm text-zinc-300">Design, conversion blocks, and local details are being assembled.</p>
          </div>
        ) : null}

        {showPreview ? (
          <section className="mt-8 space-y-5">
            <div className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900">
              <div className="border-b border-zinc-800 bg-zinc-950 px-4 py-2 text-xs font-medium text-zinc-400">
                LIVE PREVIEW
              </div>
              <iframe
                title="Generated website preview"
                src={previewUrl}
                className="h-[820px] w-full bg-white md:h-[900px]"
              />
            </div>

            <div className="flex flex-col gap-3 sm:flex-row">
              <Button onClick={handleClaim} size="lg" className="h-12 rounded-full bg-emerald-600 px-8 text-base font-bold hover:bg-emerald-500">
                Claim this website & get the code
              </Button>
              <Button onClick={resetAll} size="lg" variant="secondary" className="h-12 rounded-full px-8 font-semibold">
                Try different inputs
              </Button>
            </div>
          </section>
        ) : null}

        {showClaimSuccess ? (
          <div className="fixed inset-0 z-[70] grid place-items-center bg-black/70 p-4">
            <div className="w-full max-w-md rounded-2xl border border-zinc-700 bg-zinc-900 p-6 text-center">
              <CheckCircle2 className="mx-auto h-10 w-10 text-emerald-400" />
              <h2 className="mt-3 text-2xl font-bold">Website claimed</h2>
              <p className="mt-2 text-sm text-zinc-300">
                Your site is claimed! Welcome to your dashboard.
              </p>
              <Button onClick={() => setShowClaimSuccess(false)} className="mt-5 rounded-full bg-emerald-600 px-8 font-semibold hover:bg-emerald-500">
                Close
              </Button>
            </div>
          </div>
        ) : null}
      </div>
    </main>
  );
}
